services:
  backend:
    container_name: principium-backend-dev
    build:
      context: ./actix-backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./actix-backend/src:/app/src
      - ./actix-backend/Cargo.toml:/app/Cargo.toml
      - ./actix-backend/Cargo.lock:/app/Cargo.lock
    ports:
      - '8080:8080'
    env_file:
      - ./actix-backend/.env.dev
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: principium-db-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: principium
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
